#!/bin/bash -ux

export JOURNALCTL="/usr/bin/journalctl -o short-precise"
export SUPPORT_BUNDLE_NODE_NAME=$(hostname)

HOST_PATH=$1
BUNDLE_DIR=$2

mkdir -p $BUNDLE_DIR

curl -o collector-harvester \
  https://raw.githubusercontent.com/rancher/support-bundle-kit/refs/heads/master/hack/collector-harvester
chmod +x collector-harvester

./collector-harvester $HOST_PATH $BUNDLE_DIR