#!/bin/bash -ux

source /tmp/common
HOST_PATH=$1
BUNDLE_DIR=$2

# RKE2: Logs for the kubelet are save in rke2 agent log folder
RKE2_KUBELET_LOG_PATH=${HOST_PATH}/var/lib/rancher/rke2/agent/logs/kubelet.log

function collect_proc_mounts(){
    cp ${HOST_PATH}/proc/mounts ./proc_mounts
}

function collect_multipath_config(){
    if [ -f ${HOST_PATH}/etc/multipath.conf ]; then
        cp ${HOST_PATH}/etc/multipath.conf .
    fi
}

function collect_processes_info(){
    ps auxw > ./processes_info
}

function collect_sysinfo(){
    cd ${BUNDLE_DIR}
    mkdir -p hostinfos
    cd hostinfos

    echo -e "hostname : \n `cat ${HOST_PATH}/etc/hostname | sed "s/^/\t/"`" > hostinfo
    echo -e "os-release : \n `cat ${HOST_PATH}/etc/os-release | sed "s/^/\t/"`" >> hostinfo
    echo -e "system-info : \n `uname -a | sed "s/^/\t/"`" >> hostinfo

    # Boot Configuration
    cat ${HOST_PATH}/boot/config-$(uname -r) > kernel_config

    collect_proc_mounts
    collect_multipath_config
    collect_processes_info
}

function collect_dmesg(){
    dmesg -HTx &> dmesg.log
}

function collect_syslog(){
    # Different Linux distributions use different syslog daemons, which store log messages in different locations.
    # The common locations are /var/log/syslog and /var/log/messages.
    cp ${HOST_PATH}/var/log/syslog* .
    cp ${HOST_PATH}/var/log/messages* .
}

function collect_kubelet_log(){
    # On Linux nodes that use systemd, the kubelet and container runtime write to journald by default.
    # ref. https://kubernetes.io/docs/concepts/cluster-administration/logging/#log-location-node
    chroot ${HOST_PATH} $JOURNALCTL -r -u kubelet > kubelet.log

    # For K3s cluster
    chroot ${HOST_PATH} $JOURNALCTL -r -u k3s.service > k3s-service.log
    chroot ${HOST_PATH} $JOURNALCTL -r -u k3s-agent.service > k3s-agent-service.log

    if [ -f ${RKE2_KUBELET_LOG_PATH} ]; then
        cp ${RKE2_KUBELET_LOG_PATH} .
    fi
}

collect_longhorn_logs() {
    local src_dir
    src_dir=$(join_paths "$HOST_PATH" "$LONGHORN_LOG_PATH")

    if [ -d "$src_dir" ]; then
        cp -r "$src_dir"/* .
    else
        echo "Longhorn log directory not found: $src_dir" >&2
    fi
}

join_paths() {
    local base="$1"
    local sub="$2"
    # Remove trailing slash from base and leading slash from sub
    printf "%s/%s\n" "${base%/}" "${sub#/}"
}

function collect_logs(){
    cd ${BUNDLE_DIR}
    mkdir -p logs
    cd logs

    collect_dmesg
    collect_syslog
    collect_kubelet_log
    collect_longhorn_logs
}

collect_sysinfo
collect_logs
