#!/bin/bash -ux

HOST_PATH=$1
BUNDLE_DIR=$2

cd ${BUNDLE_DIR}

# get some host information
cp ${HOST_PATH}/etc/hostname .

# collect logs
mkdir -p logs
cd logs
dmesg &> dmesg.log

# k3s logs don't rorate well and can be huge
tail -c 10m ${HOST_PATH}/var/log/k3s-service.log > k3s-service.log
tail -c 10m ${HOST_PATH}/var/log/k3s-restarter.log > k3s-restarter.log

cp ${HOST_PATH}/var/log/qemu-ga.log* .
cp ${HOST_PATH}/var/log/messages* .
cp ${HOST_PATH}/var/log/console.log .
