#!/usr/bin/env bash

HOST_PATH=$1
BUNDLE_DIR=$2

# RKE2: Logs for the kubelet are save in rke2 agent log folder
RKE2_KUBELET_LOG_PATH=${HOST_PATH}/var/lib/rancher/rke2/agent/logs/kubelet.log

function collect_sysinfo(){
    cd ${BUNDLE_DIR}
    mkdir -p hostinfos
    cd hostinfos

    echo -e "hostname : \n `cat ${HOST_PATH}/etc/hostname | sed "s/^/\t/"`" > hostinfo
    echo -e "os-release : \n `cat ${HOST_PATH}/etc/os-release | sed "s/^/\t/"`" >> hostinfo
    echo -e "system-info : \n `uname -a | sed "s/^/\t/"`" >> hostinfo

    # Boot Configuration
    cat ${HOST_PATH}/boot/config-$(uname -r) > kernel_config
}

function collect_dmesg(){
    dmesg -HTx &> dmesg.log
}

function collect_syslog(){
    cp ${HOST_PATH}/var/log/syslog* .
}

function collect_kubelet_log(){
    # On Linux nodes that use systemd, the kubelet and container runtime write to journald by default. 
    # ref. https://kubernetes.io/docs/concepts/cluster-administration/logging/#log-location-node
    chroot ${HOST_PATH} /usr/bin/journalctl -r -u kubelet > kubelet.log
    
    if [ -f ${RKE2_KUBELET_LOG_PATH} ]; then
        cp ${RKE2_KUBELET_LOG_PATH} .
    fi
}

function collect_logs(){
    cd ${BUNDLE_DIR}
    mkdir -p logs
    cd logs

    collect_dmesg
    collect_syslog
    collect_kubelet_log
}

collect_sysinfo
collect_logs
