#!/bin/bash -e

source $(dirname $0)/version
cd $(dirname $0)/..

mkdir -p bin
if [ "$(uname)" = "Linux" ]; then
    OTHER_LINKFLAGS="-extldflags -static -s"
fi

LINKFLAGS="-X github.com/rancher/support-bundle-kit/cmd.AppVersion=$VERSION
           -X github.com/rancher/support-bundle-kit/cmd.GitCommit=$COMMIT"

CGO_ENABLED=0 GOARCH=amd64 go build -ldflags "$LINKFLAGS $OTHER_LINKFLAGS" -o bin/support-bundle-kit-amd64
CGO_ENABLED=0 GOARCH=arm64 go build -ldflags "$LINKFLAGS $OTHER_LINKFLAGS" -o bin/support-bundle-kit-arm64

# non-go scripts
cp hack/* bin
