#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/..

mkdir -p dist/artifacts
cp bin/harvester-sb-collector.sh dist/artifacts
cp bin/support-bundle-utils dist/artifacts/support-bundle-utils${SUFFIX}

IMAGE=${REPO}/harvester-support-bundle-utils:${TAG}
DOCKERFILE=Dockerfile
if [ -e ${DOCKERFILE}.${ARCH} ]; then
    DOCKERFILE=${DOCKERFILE}.${ARCH}
fi

docker build -f package/${DOCKERFILE} -t ${IMAGE} .
echo Built ${IMAGE}
