#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/..

cd $(dirname $0)/package

IMAGE=${REPO}/support-bundle-utils:${TAG}
DOCKERFILE=Dockerfile
if [ -e ${DOCKERFILE}.${ARCH} ]; then
    DOCKERFILE=${DOCKERFILE}.${ARCH}
fi

cp -r ../bin .

docker build --build-arg VERSION=${VERSION} -f ${DOCKERFILE} -t ${IMAGE} .
echo Built ${IMAGE}
