name: Master Build and Publish

on:
  push:
    branches:
      - master
      - release/v*
  schedule:
    - cron: "30 2 * * *" # daily at 02:30 AM UTC
  workflow_dispatch:

jobs:
  call-dapper-build:
    uses: ./.github/workflows/template-build.yml
    with:
      release-tag-name: ${{ github.ref_name }}-head
      push: true
    secrets: inherit
