name: Pull Request Build

on:
  pull_request:

permissions:
  contents: read

jobs:
  call-dapper-build:
    uses: ./.github/workflows/template-build.yml
    with:
      release-tag-name: pull-${{ github.event.number }}
      push: false
    secrets: inherit
