name: Tag Build and Publish

on:
  release:
    types: [published]

jobs:
  call-dapper-build:
    uses: ./.github/workflows/template-build.yml
    with:
      release-tag-name: ${{ github.event.release.tag_name }}
      push: true
      release: true
    secrets: inherit
