on:
  workflow_call:
    inputs:
      release-tag-name:
        required: true
        type: string
      push:
        required: true
        type: boolean
      release:
        required: false
        default: false
        type: boolean

env:
  PLATFORMS: linux/amd64,linux/arm64
  imageName: support-bundle-kit

jobs:
  dapper-build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3

      - name: Run dapper
        run: make ci

      - name: Docker Build
        if: ${{ inputs.push == false }}
        uses: docker/build-push-action@ca052bb54ab0790a636c9b5f226502c73d547a25 # v5
        with:
          provenance: false
          context: .
          platforms: ${{ env.PLATFORMS }}
          file: package/Dockerfile
          push: false
          tags: ${{ env.imageName }}:${{ inputs.release-tag-name }}

      - name: Login to Docker Hub
        id: login-docker
        if: ${{ inputs.push == true }}
        uses: harvester/harvester-actions/actions/login-docker-hub@f5246cd8d423922ea55141991155f4b05f665bd5 # main

      - name: Publish public ${{ env.imageName }} image
        if: ${{ inputs.push == true }}
        uses: harvester/harvester-actions/actions/publish-public-image@f5246cd8d423922ea55141991155f4b05f665bd5 # main
        with:
          context: .
          dockerfile: package/Dockerfile
          image: ${{ env.imageName }}
          tag: ${{ inputs.release-tag-name }}
          platforms: ${{ env.PLATFORMS }}
          registry: ${{ steps.login-docker.outputs.registry }}
          repository: ${{ steps.login-docker.outputs.repository }}

      - name: Login to Staging Registry
        id: login-staging
        if: ${{ inputs.push == true && inputs.release == false }}
        uses: harvester/harvester-actions/actions/login-staging-registry@f5246cd8d423922ea55141991155f4b05f665bd5 # main

      - name: Publish staging ${{ env.imageName }} image
        if: ${{ inputs.push == true && inputs.release == false }}
        uses: harvester/harvester-actions/actions/publish-prime-image@f5246cd8d423922ea55141991155f4b05f665bd5 # main
        with:
          context: .
          dockerfile: package/Dockerfile
          image: ${{ env.imageName }}
          tag: ${{ inputs.release-tag-name }}
          platforms: ${{ env.PLATFORMS }}
          registry: ${{ steps.login-staging.outputs.registry }}
          repository: ${{ steps.login-staging.outputs.repository }}

      - name: Login to Prime Registry
        id: login-prime
        if: ${{ inputs.push == true && inputs.release == true }}
        uses: harvester/harvester-actions/actions/login-prime-registry@f5246cd8d423922ea55141991155f4b05f665bd5 # main

      - name: Publish prime ${{ env.imageName }} image
        if: ${{ inputs.push == true && inputs.release == true }}
        uses: harvester/harvester-actions/actions/publish-prime-image@f5246cd8d423922ea55141991155f4b05f665bd5 # main
        with:
          context: .
          dockerfile: package/Dockerfile
          image: ${{ env.imageName }}
          tag: ${{ inputs.release-tag-name }}
          platforms: ${{ env.PLATFORMS }}
          registry: ${{ steps.login-prime.outputs.registry }}
          repository: ${{ steps.login-prime.outputs.repository }}

      - name: Prepare artifacts for the release
        if: ${{ startsWith(github.ref, 'refs/tags/') && inputs.release }}
        run: |
          cd dist/artifacts
          for arch in amd64 arm64 darwin-arm64; do
            rm -f sha256sum-$arch.txt && touch sha256sum-$arch.txt
            if [ -e support-bundle-kit-$arch ]; then
              tar zcf support-bundle-kit-$arch.tar.gz support-bundle-kit-$arch
              sha256sum support-bundle-kit-$arch.tar.gz > sha256sum-$arch.txt
            fi
          done


      - name: Publish artifacts to the release
        if: ${{ startsWith(github.ref, 'refs/tags/') && inputs.release }}
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          if gh release view ${{ github.ref_name }} > /dev/null; then
            echo ${{ github.ref_name }} release exists
          else
            gh release create ${{ github.ref_name }} --draft --notes "Draft release for ${{ github.ref_name }}"
          fi
          gh release upload ${{ github.ref_name }} dist/artifacts/support-bundle-kit-amd64.tar.gz
          gh release upload ${{ github.ref_name }} dist/artifacts/support-bundle-kit-arm64.tar.gz
          gh release upload ${{ github.ref_name }} dist/artifacts/support-bundle-kit-darwin-arm64.tar.gz
          gh release upload ${{ github.ref_name }} dist/artifacts/sha256sum-amd64.txt
          gh release upload ${{ github.ref_name }} dist/artifacts/sha256sum-arm64.txt
          gh release upload ${{ github.ref_name }} dist/artifacts/sha256sum-darwin-arm64.txt
